### ISSUE TITLE
Tracking issue of CI failures until next sync

### ISSUE THREAD

**Issue by christophfroehlich** [ros-controls/realtime_tools#239]
Rolling 3.0.0

- [ ] https://github.com/ros-controls/control_toolbox/issues/250

Jazzy 3.0.0

- [ ] https://github.com/ros-controls/control_toolbox/issues/248

Humble 2.10

- [ ] https://github.com/ros-controls/control_toolbox/issues/249
